name: Test and trigger deployement

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  deploy:
    name: Deploy to Cloudflare Pages
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Set Deploy Hook Based on Branch
        id: set_hook
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=deploy_hook::${{ secrets.DEPLOY_HOOK_MASTER }}"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=deploy_hook::${{ secrets.DEPLOY_HOOK_DEV }}"
          fi

      - name: Trigger Cloudflare Pages 
        run: curl -X POST ${{ steps.set_hook.outputs.deploy_hook }}
